tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "awscli"
brew "cmake"
brew "coreutils"
brew "cowsay"
brew "dnsmasq"
brew "git"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "mongodb", restart_service: true
brew "mysql", restart_service: true
brew "ncdu"
brew "nvm"
brew "openconnect"
brew "postgresql", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "terraform"
brew "the_silver_searcher"
brew "thefuck"
brew "yarn"
brew "vim"
brew "wget"
brew "zsh"
cask "vagrant"
cask "virtualbox"
